name: Tests execution

on: [pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install project dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test:unit